apiVersion: cluster.kbg/v1alpha1
kind: BlueGreenDeployment
metadata:
  name: myserver
spec:
  replicas: 2
  backupScaleDownPercent: 50
  #overrideColor: green
  service:
    type: NodePort
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.18.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
